### ISSUE TITLE
Figure out where and why keyterms stop producing graphs

### ISSUE THREAD

**Issue by gryBox** [gryBox/learning_map#58]
My hunch is that the "definitions" are garbage. And I need to be more discriminating when making a definition of a cluster

**Comment by gryBox** [comment]
Tried 

- [ ] Remove terms longer than 4 tokens
- [ ] Added more keywords for teaching address search
- [ ]Checked that the search is working

**Comment by gryBox** [comment]
In continuation of the last 
```
#TODO: HANDLE MISSING DEFINITIONS (SEE BLOCK 118 SIMPLE FLOW CHART)
		##2. Handle if domain def not found for end word in the graybox definition db
		if domainDef.shape[0]==0:
			print('MAKING A DEFINITION')
			# TODO: ADD TOPIC FROM WIKI using wordnet
			# Tries to make a definition for the endWrd if one does not already exchange

			try: # handle if there is no previos text
				missingDef = mmd.make_missing_def(self.endWord, self.prev_tt_corpus)
				definition_df = missingDef.make_definition()
```

**Comment by gryBox** [comment]
passed `tt_corpus` as doc instead of text

**Comment by gryBox** [comment]
#64 
#62 
#63
